//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizadorMusicas.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMidia
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> idGenero { get; set; }
        public Nullable<int> idAlbum { get; set; }
        public Nullable<int> idArtista { get; set; }
    }
}
